disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "io0SaY"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
author = { name = "io0SaY", email = "", image = "", imageQuality = 96, headline = "好奇心 同理心 责任心", bio = "A little bit about me", links = [ { github = "" } ] }
logo = ""
secondaryLogo = ""
